// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlqdolkvsitqyevdpqdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhscWRvbGt2c2l0cXlldmRwcWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjI2OTEsImV4cCI6MjA2Mzk5ODY5MX0.AkO74uIFGbetyC7wfWuK1R6OG2MjYuwbOqIA4QW-ITg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);